# Generated by Django 2.0.2 on 2018-10-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181005_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='tag_set',
        ),
    ]
