# Generated by Django 2.0.2 on 2018-10-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181005_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_set',
            new_name='comment',
        ),
    ]
