# Generated by Django 2.0.2 on 2018-10-29 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181029_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compcategory',
            name='cate_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CompCategory'),
        ),
    ]
