# Generated by Django 2.0.2 on 2018-10-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181029_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comp_cate',
            field=models.ManyToManyField(blank=True, to='accounts.CompCategory'),
        ),
    ]
