# Generated by Django 2.0.2 on 2018-10-31 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_info', '0001_initial'),
        ('payment', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_calc', models.BooleanField()),
                ('cont_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_clt', to='client_info.ClientInfo')),
                ('cont_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment')),
                ('cont_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_prd', to='product.Product')),
            ],
        ),
    ]
