# Generated by Django 2.0.4 on 2018-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='use_1',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='use_2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
