# Generated by Django 2.0.1 on 2018-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
