# Generated by Django 2.0.1 on 2018-03-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180322_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
