FROM        ubuntu:16.04
MAINTAINER  makingfunk0@gmail.com

RUN         apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN         apt-get -y install python3
RUN         apt-get -y install python3-pip
RUN         apt-get -y install nginx
RUN         apt-get -y install supervisor

RUN         pip3 install django
RUN         pip3 install uwsgi
