# Generated by Django 2.0.2 on 2018-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_ceo', models.CharField(max_length=10)),
                ('clt_name', models.CharField(max_length=20)),
                ('clt_biz_num', models.CharField(max_length=13)),
                ('clt_cate_1', models.CharField(max_length=10)),
                ('clt_cate_2', models.CharField(max_length=10)),
                ('clt_post', models.CharField(max_length=7)),
                ('clt_addr', models.TextField()),
                ('clt_call', models.CharField(max_length=13)),
                ('clt_phone', models.CharField(max_length=13)),
                ('clt_fax', models.CharField(max_length=13)),
                ('clt_email', models.CharField(max_length=30)),
                ('clt_page', models.TextField()),
                ('clt_person', models.CharField(max_length=10)),
            ],
        ),
    ]
