# Generated by Django 2.0.2 on 2018-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_call',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_cate_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_cate_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_fax',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_person',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clt_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
