# Generated by Django 2.0.2 on 2018-10-31 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_money', models.CharField(max_length=14)),
                ('bank_name', models.CharField(max_length=10)),
                ('bank_in_name', models.CharField(max_length=10)),
                ('bank_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PayCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_sell', models.CharField(max_length=14)),
                ('card_comp', models.CharField(max_length=10)),
                ('card_num', models.CharField(max_length=20)),
                ('card_sell_date', models.DateField()),
                ('card_life', models.CharField(max_length=8)),
                ('card_approval_num', models.CharField(max_length=10)),
                ('card_plan', models.IntegerField()),
                ('card_money', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_money', models.CharField(max_length=14)),
                ('pmt_sell', models.CharField(max_length=14)),
                ('pmt_tax', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_mtd', models.CharField(choices=[('card', '카드'), ('bank', '현금')], max_length=10)),
                ('pmt_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.PayBank')),
                ('pmt_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.PayCard')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='pmt_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentComp'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pmt_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentMethod'),
        ),
    ]
