# Generated by Django 2.0.2 on 2018-10-31 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_company', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='paycard',
            name='card_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.CardComp'),
        ),
    ]
