# Generated by Django 2.0.2 on 2018-11-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181031_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='pmt_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PayBank'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='pmt_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PayCard'),
        ),
    ]
