# Generated by Django 2.0.2 on 2018-11-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20181101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pmt_sell',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pmt_tax',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
