# Generated by Django 2.0.2 on 2018-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181101_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pmt_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pmt_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
