# Generated by Django 2.0.1 on 2018-03-19 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('end_intern', models.DateTimeField(default=datetime.datetime(2018, 4, 18, 11, 14, 11, 421578))),
            ],
        ),
    ]
