# Generated by Django 2.0.1 on 2018-03-19 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0002_auto_20180319_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='gps',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='end_intern',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 17, 12, 26, 16, 500983)),
        ),
    ]
