# Generated by Django 2.0.1 on 2018-03-20 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0004_auto_20180320_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='end_intern',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 14, 4, 31, 13645)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='lat',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='lng',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
