# Generated by Django 2.0.4 on 2018-11-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_code', models.AutoField(primary_key=True, serialize=False, verbose_name='부서코드')),
                ('team_name', models.CharField(max_length=10, verbose_name='부서명')),
                ('team_deps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team', verbose_name='상위부서')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(max_length=20, verbose_name='닉네임'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Team', verbose_name='부서'),
            preserve_default=False,
        ),
    ]
