# Generated by Django 2.0.4 on 2018-11-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181118_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_deps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Team', verbose_name='상위부서'),
        ),
    ]
