# Generated by Django 2.0.2 on 2018-11-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('lv1', '대표이사'), ('lv2', '이사'), ('lv3', '부장'), ('lv4', '차장'), ('lv5', '실장'), ('lv6', '본부장'), ('lv7', '팀장'), ('lv8', '과장'), ('lv9', '주임'), ('lv10', '대리')], max_length=20, verbose_name='직급'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(max_length=10, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teamname', to='accounts.Team', verbose_name='직급'),
        ),
    ]
