# Generated by Django 2.0.2 on 2018-11-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181030_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('lv1', '대표이사'), ('lv2', '이사'), ('lv3', '부장'), ('lv4', '차장'), ('lv5', '실장'), ('lv6', '본부장'), ('lv7', '팀장'), ('lv8', '과장'), ('lv9', '주임'), ('lv10', '대리')], max_length=20),
        ),
    ]
