# Generated by Django 2.0.2 on 2018-10-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_name', models.CharField(max_length=50, unique=True)),
                ('prod_code', models.AutoField(primary_key=True, serialize=False)),
                ('prod_act', models.BooleanField()),
                ('prod_memo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
